# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('satisfy_rate', models.IntegerField()),
                ('fresh_rate', models.IntegerField()),
            ],
        ),
    ]
