# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='know_way',
            field=models.IntegerField(default=1),
        ),
    ]
