# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20160311_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='involved_type',
            field=models.IntegerField(default=0),
        ),
    ]
