# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 04:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0011_auto_20160311_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 4, 49, 41, 586571, tzinfo=utc)),
        ),
    ]
